title: Half-Truth
logo: /assets/img/logo.png

show_downloads: false
google_analytics: G-R2SM80ZXG0
timezone: Asia/Shanghai
remote_theme: pages-themes/minimal@v0.2.0

plugins:
  - jekyll-remote-theme
  - jekyll-feed


feed:
  posts_limit: false

